export const questions = [
  {
    id: 1,
    category: "JavaScript",
    question: "Which keyword is used to declare a block-scoped variable in JavaScript?",
    options: ["var", "let", "def", "dim"],
    answer: "let",
  },
  {
    id: 2,
    category: "JavaScript",
    question: "What does the '===' operator check in JavaScript?",
    options: [
      "Value only",
      "Type only",
      "Value and type",
      "Neither value nor type",
    ],
    answer: "Value and type",
  },
  {
    id: 3,
    category: "React",
    question: "Which hook is used to manage state in a functional React component?",
    options: ["useEffect", "useRef", "useState", "useContext"],
    answer: "useState",
  },
  {
    id: 4,
    category: "React",
    question: "What does JSX stand for?",
    options: [
      "JavaScript XML",
      "Java Syntax Extension",
      "JSON XML",
      "JavaScript Extension",
    ],
    answer: "JavaScript XML",
  },
  {
    id: 5,
    category: "HTML",
    question: "Which HTML tag is used to link an external CSS file?",
    options: ["<style>", "<css>", "<link>", "<script>"],
    answer: "<link>",
  },
  {
    id: 6,
    category: "CSS",
    question: "Which CSS property controls the space between elements?",
    options: ["padding", "margin", "spacing", "border"],
    answer: "margin",
  },
  {
    id: 7,
    category: "JavaScript",
    question: "What method converts a JSON string to a JavaScript object?",
    options: ["JSON.stringify()", "JSON.parse()", "JSON.convert()", "JSON.decode()"],
    answer: "JSON.parse()",
  },
  {
    id: 8,
    category: "General CS",
    question: "What does API stand for?",
    options: [
      "Application Programming Interface",
      "Applied Program Interaction",
      "Automated Programming Input",
      "Application Process Interaction",
    ],
    answer: "Application Programming Interface",
  },
  {
    id: 9,
    category: "JavaScript",
    question: "Which array method creates a new array with all elements that pass a test?",
    options: [".map()", ".reduce()", ".filter()", ".find()"],
    answer: ".filter()",
  },
  {
    id: 10,
    category: "General CS",
    question: "What does HTTP stand for?",
    options: [
      "HyperText Transfer Protocol",
      "High Text Transfer Process",
      "HyperText Transit Program",
      "High Transfer Text Protocol",
    ],
    answer: "HyperText Transfer Protocol",
  },
];
